### python异步 ###

#### 简要说明 ####
协程就是异步，异步就是在同一时间内并发处理多个任务的东东
>协程通过 async/await 语法进行声明，是编写异步应用的推荐方式

py3.7版本自带asyncio模块，其他版本请自行安装


#### 简单例子 ####
```python
import asyncio
async def main():
    print('demo')
    await asyncio.sleep(4)
    print('demo2')

asyncio.run(main())
```

协程通过async/await语法进行声明，asyncio.run()函数是用于一运行个使用async的函数

```
async的中文意思是:异步
await的中文意思是：等待
```

第二个例子
```python
import asyncio
import time

async def demo(delay,what):
    await asyncio.sleep(delay)
    print(what)

async def main():
    print('开始时间:{}'.format(time.strftime('%X')))
    await demo(1,'demo')
    await demo(2,'demon')
    print('结束时间:{}'.format(time.strftime('%X')))

asyncio.run(main())
```
预期输出
![](https://s2.ax1x.com/2019/04/04/A26jTH.png)


asyncio.create_ask()函数用来并发运行作为asyncio任务的多个协程
```python
import asyncio
import time

async def demo(delay,what):
    await asyncio.sleep(delay)
    print(what)

async def main():
    print('开始时间:{}'.format(time.strftime('%X')))
    task=asyncio.create_task(demo(1,'demo'))
    task2=asyncio.create_task(demo(2,'demon'))
    await task
    await task2
    print('结束时间:{}'.format(time.strftime('%X')))

asyncio.run(main())
```
注意，预期的输出显示代码段的运行时间比之前快了 1 秒:
![](https://s2.ax1x.com/2019/04/04/A2gK5d.png)

#### 可等待对象 ####
如果一个对象可以在await语句中使用，那么它就是可等待对象。许多asyncio API都被设计为可等待
对象

<b>协程</b>
Python 协程属于 可等待 对象，因此可以在其他协程中被等待:
```python
import asyncio

async def nested():
    return 42

async def main():
    print(await nested())
asyncio.run(main())
```
<b>重要</b>:在文本文档中“协程”可用来表示两个紧密关系的概念：
* 协程函数,定义形式为async def的函数
* 协程对象,调用协程函数所返回的对象

<b>任务</b>
任务被用来设置日程以便并发执行协程
当一个协程通过 asyncio.create_task() 等函数被打包为一个 任务，该协程将自动排入日程准备立即运行:
```python
import asyncio

async def nested():
    return 42

async def main():
    task=asyncio.create_task(nested())
    await task
asyncio.run(main())
```

#### 运行asyncio程序 ####
asyncio.run(coro,debug=False)
此函数运行传入的协程，负责管理asyncio事件循环并完结异步生成器
当有其他asyncio事件循环在同一线程运行时，此函数不能被调用
如果debug为True，事件循环将以调试模式运行
此函数总是会创建一个新的事件循环并在结束时关闭之。它应当被用作asyncio程序的主入口点，理想情况下应当只被调用一次

#### 创建任务 ####
asyncio.create_task(coro)
将coro协程打包为一个Task排入日程准备执行。返回Task对象
该任务会在get_running_loop()返回的循环中执行
此函数 在 Python 3.7 中被加入。在 Python 3.7 之前，可以改用低层级的 asyncio.ensure_future() 函数。

#### 休眠 ####
休眠
coroutine asyncio.sleep(delay, result=None, *, loop=None)
阻塞 delay 指定的秒数。

<b>注意:</b>
如果一个对象可以在 await 语句中使用，那么它就是 可等待 对象。许多 asyncio API 都被设计为接受可等待对象。

如果指定了 result，则当协程完成时将其返回给调用者。
sleep() 总是会挂起当前任务，以允许其他任务运行。
loop 参数已弃用，计划在 Python 3.10 中移除。
例子:
```python
import asyncio
import datetime

async def display_date():
    loop = asyncio.get_running_loop()
    end_time = loop.time() + 5.0
    while True:
        print(datetime.datetime.now())
        if (loop.time() + 1.0) >= end_time:
            break
        await asyncio.sleep(1)

asyncio.run(display_date())
```

#### 并发运行任务 ####
```python
import asyncio
import datetime
import requests

headers={'user-agent':'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36'}
async def display_date(cd):
    for i in range(0,cd):
        print('haq')
    await asyncio.sleep(1)

async def dg(cd):
    for i in range(0, cd):
        print('haq')

async def main():
    await asyncio.gather(display_date(10),dg(20))

asyncio.run(main())
```

asyncio.gather(*aws, loop=None, return_exceptions=False)
aws:并发运行aws序列中的可等待对象,如果 aws 中的某个可等待对象为协程，它将自动作为一个任务加入日程。
如果所有可等待对象都成功完成，结果将是一个由所有返回值聚合而成的列表。结果值的顺序与 aws 中可等待对
象的顺序一致。


return_exceptions:为 False (默认)，所引发的首个异常会立即传播给等待 gather() 的任务。aws 
序列中的其他可等待对象 不会被取消 并将继续运行。

异常测试
![](https://s2.ax1x.com/2019/04/04/A24nVf.md.png)
可以发现，即使有异常异步也会运行到最后

如果 gather() 被取消，所有被提交 (尚未完成) 的可等待对象也会 被取消。
如果 aws 序列中的任一 Task 或 Future 对象 被取消，它将被当作引发了 CancelledError 一样处理 -- 在此情况下 gather() 调用 不会 被取消。这是为了防止一个已提交的 Task/Future 被取消导致其他 Tasks/Future 也被取消。

#### 屏蔽取消操作 ####
asyncio.shield(aw,loop=None)
保护一个 可等待对象 防止其被 取消。
如果 aw 是一个协程，它将自动作为任务加入日程。
例子：
```python
import asyncio

urlsq=['https://www.baidu.com','https://www.google.com','https://www.bing.com']

headers={'user-agent':'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36'}
async def display_date(cd):
    print(cd)

async def main():
    for g in urlsq:
        await asyncio.shield(asyncio.gather(display_date(g)))

asyncio.run(main())
```
这个函数说白了就是错误的时候，用于不取消指定协程吧= =，一般好像用不到

#### 超时 ####
asyncio.wait_for(aw,timeout)
aw为你要设置的协程
timeout你设置超时的时间

例如：
```
import asyncio

urlsq=['https://www.baidu.com','https://www.google.com','https://www.bing.com']

headers={'user-agent':'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36'}
async def display_date(cd):
    print(cd)

async def main():
    for g in urlsq:
        await asyncio.wait_for(asyncio.gather(display_date(g)),timeout=2)

asyncio.run(main())
```

先学那么多，毕竟有些用不到
协程文档：https://docs.python.org/zh-cn/3/library/asyncio-task.html#id12
